{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "plant_id", "label": "Selected Plant", "query": "1" },
   { "name": "arm_pos" }
  ]
 },
 "panels": [
  { "title": "Robot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Set Robot State/Activity",
   "type": "canvas",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Activity/State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"value_state_properties_value\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Arm Position",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\r\nfrom(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> limit(n: 1) \r\n  |> map(fn: (r) => ({ r with my_constant: \"${arm_pos}\" }))\r\n  |>keep(columns: [\"my_constant\"])\r\n  |> rename(columns: {my_constant: \"_value\"})"
    }
   ]
  },
  {
   "title": "Position",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"value_position_properties_value\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Plants",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true
  },
  {
   "title": "3D Greenhouse",
   "type": "ertis-unity-panel",
   "gridPos": { "h": 13, "w": 14, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "import \"strings\"\r\nimport \"join\"\r\n\r\nplant_age = from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"value_datetime_planted_properties_value\"\r\n  )\r\n    |>last()\r\n  |> keep(fn: (column) => column =~ /value/ or column =~ /topic/)\r\n  |>keep(columns: [\"_value\",\"topic\"])\r\n   |> map(fn: (r) => {\r\n    parts = strings.split(v: r.topic, t: \"_\")\r\n    return { r with plant_id: parts[length(arr: parts) - 1] }\r\n  })\r\n  |>drop(fn: (column) => column  =~ /topic/)\r\n      |> rename(columns: {_value: \"age\"})\r\n        |> yield(name: \"plant_age\")\r\n\r\nrobot_pos=from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"value_position_properties_value\"\r\n  )\r\n  |> last()\r\n    |>keep(fn: (column) => column  == \"_value\")\r\n            |> set(key: \"temp_id\", value: \"id\")\r\n\r\n          |> rename(columns: {_value: \"position\"})\r\n\r\n\r\nrobot_action = from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"value_action_properties_value\"\r\n  )\r\n  |> last()\r\n    |>keep(columns: [\"_value\",\"_time\"])\r\n        |> set(key: \"temp_id\", value: \"id\")\r\n\r\n          |> rename(columns: {_value: \"action\"})\r\n\r\njoin.full(\r\n  left:robot_pos,\r\n  right: robot_action,\r\n  on: (l,r) => l.temp_id == r.temp_id,\r\n  as: (l, r) => ({position:l.position,action:r.action,time:r._time})\r\n)\r\n"
    },
    {}
   ]
  },
  {
   "title": "Do at plant ${plant_id}:",
   "type": "canvas",
   "gridPos": { "h": 7, "w": 8, "x": 14, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Plant Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"value_health_properties_value\"\r\n    and r.topic =~ /plant_${plant_id}$/\r\n  )\r\n  |> keep(columns: [\"_value\"])\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Ripeness",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"value_ripeness_properties_value\" and\r\n     r.topic =~ /plant_${plant_id}$/\r\n  )\r\n  |> keep(columns: [\"_value\"])\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Soil Moisture",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"value_soil_moisture_properties_value\"\r\n    and r.topic =~ /_${plant_id}$/\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Soil Nutrient Level",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"value_soil_nutrients_properties_value\"\r\n    and r.topic =~ /_${plant_id}$/\r\n  )\r\n  |> last()"
    }
   ]
  },
  { "title": "Irrigation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Flow rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"value_flow_rate_properties_value\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  { "title": "Environment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"value_humidity_properties_value\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"value_temperature_properties_value\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Light",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"value_light_properties_value\"\r\n  )\r\n  |> last()"
    }
   ]
  }
 ]
}